name: Run Mobile E2E Tests with BrowserStack

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Start BrowserStack Local
        run: npx browserstack-local --key ${{ secrets.BROWSERSTACK_ACCESS_KEY }} &

      - name: Run Mobile E2E tests on BrowserStack
        run: npm run wdio-ci

      - name: Generate Allure report
        run: npm run report

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: mobile-test-report
          path: allure-report/
