name: Run Mobile E2E Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        run: |
          docker pull android/emulator:latest
          docker run -d --name android-emulator android/emulator:latest

      - name: Start Android Emulator
        run: |
          docker exec -d android-emulator /bin/bash -c "emulator -avd Pixel_3a_API_29 -no-window -gpu off -qemu -m 2048"
          # Aguarda o emulador ser inicializado
          sleep 60  # Ajuste o tempo de espera conforme necessário

      - name: Install dependencies
        run: npm ci

      - name: Install Appium
        run: npm install -g appium

      - name: Install UiAutomator2 driver
        run: appium driver install uiautomator2

      - name: Start Appium server
        run: appium --log appium.log &

      - name: Run Mobile E2E tests
        run: npm run wdio-ci

      - name: Generate Allure report
        run: npm run report
          
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: mobile-test-report
          path: allure-report/
